#' @title Sampled Data For Strong Null Analysis
#'
#' @description A data structure with a strong null effect for testing purposes, and running examples
#'
#' @format A \code{tibble}, simulating a within subject experiment with a single independent and dependent variables.
#' The experiment includes 100 participants, 2 conditions, and 200 trials per condition.
#' Strong null effect was generated by creating a fixed null effect for all participants.
#' The tibble includes3 columns, which are:
#' \describe{
#' \item{id}{the id of each participant}
#' \item{condition}{the independent variable}
#' \item{var}{the dependent measure}
#' }
"sampled_data_strong"
